- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-it/strings.xml
The PR is about adding Italian and Spanish as supported languages in the app.
```gradle
```
> Added spanish and italian translations for the app

- app/build.gradle
- app/src/androidTest/java/com/skydoves/pokedex/DetailActivityInjectionTest.kt
- app/src/main/java/com/skydoves/pokedex/di/AssistedInjectModule.kt
- app/src/main/java/com/skydoves/pokedex/ui/details/DetailActivity.kt
- app/src/main/java/com/skydoves/pokedex/ui/details/DetailViewModel.kt
- app/src/test/java/com/skydoves/pokedex/viewmodel/DetailViewModelTest.kt
- dependencies.gradle
Hi skydoves, this is great work. I'm adding asssited inject in `DetailViewModel` so the view no need to assign pokemon name by function instead of using constructor
feature improvement
```gradle
```
> add assisted inject

- app/build.gradle
- app/src/main/java/com/skydoves/pokedex/model/Pokemon.kt
- dependencies.gradle
Migrate to Kotlin Parcelize plugin, Kotlin 1.4.20
> Migrate to Kotlin Parcelize plugin

- .github/workflows/android.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/skydoves/pokedex/binding/RecyclerViewBinding.kt
- app/src/main/java/com/skydoves/pokedex/persistence/PokemonDao.kt
- app/src/main/java/com/skydoves/pokedex/ui/adapter/PokemonAdapter.kt
- app/src/main/java/com/skydoves/pokedex/ui/main/MainViewModel.kt
- app/src/main/res/layout/activity_detail.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/item_pokemon.xml
- app/src/main/res/layout/toolbar_home.xml
- app/src/test/java/com/skydoves/pokedex/viewmodel/MainViewModelTest.kt
- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
Supports screen rotation and restoring the scroll position after screen rotations.
> Supports screen rotation and restoring the scroll position after screen rotations

- dependencies.gradle
> Bump hilt to 2.37

- dependencies.gradle
This version number has been useless
> remove useless version

- app/src/main/java/com/skydoves/pokedex/di/DispatcherModule.kt
- app/src/main/java/com/skydoves/pokedex/di/RepositoryModule.kt
- app/src/main/java/com/skydoves/pokedex/repository/DetailRepository.kt
- app/src/main/java/com/skydoves/pokedex/repository/MainRepository.kt
- app/src/test/java/com/skydoves/pokedex/repository/DetailRepositoryTest.kt
- app/src/test/java/com/skydoves/pokedex/repository/MainRepositoryTest.kt
- app/src/test/java/com/skydoves/pokedex/viewmodel/DetailViewModelTest.kt
- app/src/test/java/com/skydoves/pokedex/viewmodel/MainViewModelTest.kt
- Added a new DispatcherModule.
> [DI] DispatcherModule

- app/src/main/java/com/skydoves/pokedex/ui/main/MainViewModel.kt
- app/src/test/java/com/skydoves/pokedex/viewmodel/MainViewModelTest.kt
parameter SavedStateHandle of MainViewModel class was never used so i deleted it
- [x ] Bugfix (non-breaking change which fixes an issue)
```gradle
```
> [Delete] remove SavedStateHandle parameter in MainViewModel.kt

- .github/workflows/android.yml
- app/build.gradle
- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
> Update AGP to 7.0.2

- app/src/main/java/com/skydoves/pokedex/ui/details/DetailActivity.kt
- app/src/main/java/com/skydoves/pokedex/ui/main/MainActivity.kt
- build.gradle
- dependencies.gradle
> Bump dependencies

- app/build.gradle
- build.gradle
- dependencies.gradle
> Tweak hilt dependencies

- dependencies.gradle
Bump AGP and library dependencies.
> Bump AGP and library dependencies

- app/src/main/java/com/skydoves/pokedex/di/NetworkModule.kt
- app/src/test/java/com/skydoves/pokedex/network/ApiAbstract.kt
Migrate to sandwich [1.2.4](https://github.com/skydoves/sandwich/releases/tag/1.2.4).
> Migrate to sandwich 1.2.4

- app/src/main/java/com/skydoves/pokedex/repository/DetailRepository.kt
- dependencies.gradle
Update compile & target SDK to 32.
> Update compile & target SDK to 32

- gradle/libs.versions.toml
Update toml to refer versions.
> Update toml to refer versions

- app/build.gradle.kts
- app/src/main/kotlin/com/skydoves/pokedex/ui/details/DetailActivity.kt
- build.gradle.kts
- core-data/build.gradle.kts
- core-database/build.gradle.kts
- core-model/build.gradle.kts
- core-network/build.gradle.kts
- gradle/libs.versions.toml
> Migrate hilt kapt to ksp

- app/build.gradle.kts
- gradle/libs.versions.toml
Fix hilt couldn't resolve generated classes from databinding.
> Fix hilt couldn't resolve generated classes from databinding

- core-network/src/main/kotlin/com/skydoves/pokedex/core/network/di/NetworkModule.kt
- core-network/src/main/kotlin/com/skydoves/pokedex/core/network/model/mapper/ErrorResponseMapper.kt
- gradle/libs.versions.toml
> Bump Sandwich to 2.0.0

- app/build.gradle.kts
- benchmark/build.gradle.kts
- core-data/build.gradle.kts
- core-database/build.gradle.kts
- core-model/build.gradle.kts
- core-network/build.gradle.kts
- core-test/build.gradle.kts
- gradle.properties
Use k2 experimental and kapt2.
> Use k2 experimental and kapt2

- .gitignore
- app/build.gradle.kts
- benchmark/build.gradle.kts
- buildSrc/src/main/kotlin/com/skydoves/pokedex/Configuration.kt
- core-data/build.gradle.kts
- core-database/build.gradle.kts
- core-model/build.gradle.kts
- core-network/build.gradle.kts
- core-test/build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
* Applied [com.android.settings](https://developer.android.com/reference/tools/gradle-api/8.3/null/com/android/build/gradle/SettingsPlugin) plugin to setup minSdk and compileSdk
* Ignore some flies which are generated by Eclipse JDT (or VSCode java tools)
* Revert ksp version to fix #149
```gradle
```
> Applied com.android.settings plugin

- app/build.gradle.kts
- benchmark/build.gradle.kts
- build.gradle.kts
- buildSrc/src/main/kotlin/com/skydoves/pokedex/Configuration.kt
- core-data/build.gradle.kts
- core-database/build.gradle.kts
- core-model/build.gradle.kts
- core-network/build.gradle.kts
- core-test/build.gradle.kts
- gradle/libs.versions.toml
* Include change from #154
* Clean up duplicated AGP configurations
* using androidx vectordrawable
* bytecode version setting
* lint configuration
* move version information to version catalogs
* jvm bytecode version
* targetSdk
```gradle
```
> Clean up duplicated configurations

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- benchmark/build.gradle.kts
- build.gradle.kts
- core-data/src/main/AndroidManifest.xml
- core-database/src/main/AndroidManifest.xml
- core-model/src/main/AndroidManifest.xml
- core-network/src/main/AndroidManifest.xml
- core-test/src/main/AndroidManifest.xml
- settings.gradle.kts
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Clean up deprecated Gradle DSL usages.
* Clean up package name on AndroidManifest.xml files.
* Clean up deprecated kotlin compiler option.
```gradle
```
> Clean up deprecated

- app/src/main/res/layout/activity_detail.xml
- app/src/main/res/layout/item_pokemon.xml
- core-model/src/main/kotlin/com/skydoves/pokedex/core/model/Pokemon.kt
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
a very small non-breaking change capitalize the first letter of the string i.e pikachu -> Pikachu
this PR closes the Issue https://github.com/skydoves/Pokedex/issues/156
```gradle
```
> Refactor: Capitalize first letter of the string

- app/build.gradle.kts
- app/src/main/kotlin/com/skydoves/pokedex/binding/ViewBinding.kt
- gradle/libs.versions.toml
- settings.gradle.kts
> Migrate to androidx-palette
